version: '3'
env:
  TaskInfo: "Create"

tasks:
  build:
    cmds:
      - kind create cluster --name=simple-cluster --config simple-cluster.yaml
      - helm repo add istio https://istio-release.storage.googleapis.com/charts
      - helm install istio-base istio/base -n istio-system --create-namespace
      - helm install istiod istio/istiod -n istio-system --wait
      - kubectl label ns default istio-injection=enabled --overwrite
      - kubectl wait pods --for=condition=Ready -l app=istiod -n istio-system
      - helm install istio-ingressgateway istio/gateway -n istio-system
      - kubectl patch service/istio-ingressgateway -n istio-system --patch-file manifests/patches/gateway-svc-patch.yaml
      - helm install istio-egressgateway istio/gateway -n istio-system
  destroy:
    cmds:
      - kind delete cluster --name simple-cluster
  lab:
    cmds:
      - echo "Write your essential build commands here"
#      - kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.18/samples/addons/jaeger.yaml
      - kubectl apply -f ./manifests/services/jaeger.yaml
#      - kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.18/samples/addons/prometheus.yaml
      - kubectl apply -f ./manifests/services/prometheus.yaml
#      - kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.18/samples/addons/grafana.yaml
      - kubectl apply -f ./manifests/services/grafana.yaml
#      - kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.18/samples/addons/kiali.yaml
      - kubectl apply -f ./manifests/services/kiali.yaml
#      - kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.yaml
      - kubectl apply -f ./manifests/services/cert-manager.yaml
      - kubectl apply -f ./manifests/apps/grafana/gateway.yaml
      - kubectl apply -f ./manifests/apps/kiali-gateway/gateway.yaml
  test:
    cmds:
      - echo "Write your tests here"

