version: '3'
env:
  TaskInfo: "Create"

tasks:
  build:
    cmds:
      - kind create cluster --name=simple-cluster --config simple-cluster.yaml
  destroy:
    cmds:
      - kind delete cluster --name simple-cluster
  lab:
    cmds:
      - echo "poc lab commands"
  test:
    cmds:
      - echo "tests commmands"

