version: '3'
env:
  TaskInfo: "Create"

tasks:
  build-it:
    cmds:
      - kind create cluster --name=simple-cluster --config simple-cluster.yaml
  destroy-it:
    cmds:
      - kind delete cluster --name simple-cluster
  lab-it:
    cmds:
      # install the load balancer
      - go install sigs.k8s.io/cloud-provider-kind@latest
      - echo "in separate console start the load balancer in the foreground with sudo cloud-provider-kind"
      - echo "continue with 'task lab-it-2'"
  lab-it-2:
    cmds:
      - kubectl apply -f https://kind.sigs.k8s.io/examples/loadbalancer/usage.yaml
      - bash ./test-it.sh

