version: '3'
env:
  TaskInfo: "Create"

tasks:
  build-it:
    cmds:
      - kind create cluster --name=simple-cluster --config simple-cluster.yaml
  destroy-it:
    cmds:
      - kind delete cluster --name simple-cluster
  lab-it:
    cmds:
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
      - kubectl label nodes simple-cluster-worker ingress-ready=true
      - kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=190s
      - kubectl apply -f app-podinfo.yaml
