version: '3'
env:
  TaskInfo: "Create"

tasks:
  build:
    cmds:
      - kind create cluster --name=simple-cluster --config simple-cluster.yaml
  destroy:
    cmds:
      - kind delete cluster --name simple-cluster
  lab:
    cmds:
      - echo "Installing kube prometheus stack"
      - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      - helm install kps oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
      - echo "Priting the admin password:"
      - kubectl --namespace default get secrets kps-grafana -o jsonpath="{.data.admin-password}" | base64 -d ; echo
  test:
    cmds:
      - echo "tests commmands"

